name: tmdb_dart
version: 0.2.2
description: >-
  Type Safe API client for The Movie Database API (v3)[https://developers.themoviedb.org/3/]
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://github.com/Kerego/tmdb_dart
dependencies:
  http: ^1.1.0
